jaffle_shop:
  target: dbt_sl_test
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_TEST_DB_HOST', 'localhost') }}"
      user: myuser
      password: mypassword
      port: "{{ env_var('POSTGRES_TEST_DB_PORT', 6543) | as_number }}"
      dbname: mydb # or database instead of dbname
      schema: dev
      threads: 6
    dbt_sl_test:
      type: postgres
      host: "{{ env_var('POSTGRES_TEST_DB_HOST', 'localhost') }}"
      user: myuser
      password: mypassword
      port: "{{ env_var('POSTGRES_TEST_DB_PORT', 6543) | as_number }}"
      dbname: mydb # or database instead of dbname
      schema: dbt_sl_test
      threads: 6